### ISSUE TITLE
데이터 샘플 확인

### ISSUE THREAD

**Issue by qudgns5129** [qudgns5129/pill_classification#1]
데이터 샘플  
![image](https://user-images.githubusercontent.com/47845170/95548662-8aee7480-0a40-11eb-9c8f-316c62ca4c60.png)
![image](https://user-images.githubusercontent.com/47845170/95548692-993c9080-0a40-11eb-94af-56f5ab35963c.png)
![image](https://user-images.githubusercontent.com/47845170/95548714-a35e8f00-0a40-11eb-9b27-b5d1c9bd3c60.png)
  
이러한 형식으로 총 8,822개의 데이터가 .jpg 형식으로 저장되어 있습니다.
  
[데이터 출처 Link](https://www.kaggle.com/dhuh137/pillbox?select=pillbox_production_images_full_201812, 'data_link')

**Comment by bytecell** [comment]
55개의 column 이 있다고 나오네.
이제부터는 문제 정의를 해보도록 하자.

어떤 column 에 있는 값을 맞출지 골라봐-

**Comment by qudgns5129** [comment]
우선 has_image 칼럼이 TRUE값인 것들만 가져오고, medicine_name칼럼을 맞추는 걸 목표로 할 거 같습니다.

**Comment by bytecell** [comment]
오키. 그럼 데이터 전체를 다운받아보고,
데이터 중에서 사용할 row와 column 을 추리는 작업부터 시작해보자.

위 작업이 되고 나면,
데이터로부터 feature 정의할 방법을 생각해봐.
image 만 사용할지, 아니면 다른 attribute 도 feature로 쓸지..

**Comment by qudgns5129** [comment]
그런데 medicine_name칼럼에 총 9670개의 unique value가 있는데 분류를할때 다 다른 레이블로 예측해버리면 어떻게되나요?

**Comment by bytecell** [comment]
한 그림에 여러 개의 약이 있는경우는 없어?
Unique label 개수가 줄어들거같은데.

**Comment by qudgns5129** [comment]
한 그림에 하나의 약만 있는 거 같습니다!  
데이터를 우선 필터링 한 이후에 중점적으로 확인해봐야 할 부분인 거 같습니다.

**Comment by bytecell** [comment]
응, medicine_name 칼럼의 unique value 들을 한번 살펴봐봐.
혹시 2개 이상의 이름이 들어있지는 않은지..

**Comment by qudgns5129** [comment]
확인 결과 medicine_name 칼럼에 'butalbital and acetaminophen'과 같이 'and'로 이어진 약 이름이나 'Dextroamphetamine Saccharate, Amphetamine Aspartate Monohydrate, Dextroamphetamine Sulfate and Amphetamine Sulfate'과 같이 ','로 연결관 약 이름을 발견하였습니다!

**Comment by qudgns5129** [comment]
그리고 새롭게 알아낸 사실로는  
- 분류할 class개수는 1979 개이며, 전체 이미지 개수는 8781개
- 'splimage' 칼럼의 벨류와 이미지의 이름이 매칭되는 것을 확인
- 'splimprint' 칼럼의 벨류는 약에 프린팅된 텍스트임

**Comment by qudgns5129** [comment]
저는 splimprint와 이미지에서 도출된 정보로만 학습하는 모델을 만들려합니다

**Comment by qudgns5129** [comment]
제완이형이 정리하신 연구관련 자료 : https://www.notion.so/5e21edcaef404e35aacc6538d7d3bb7d

**Comment by bytecell** [comment]
그렇구나.

이제부터는 '비교대상', 즉 최근에 수행된 연구들 중에서 실험을 통해 비교할 'rival method'를 정하도록 하자.

찾을 때,
github 등에 코드를 공개해놓은 것이면 가장 좋고,
코드와 데이터까지 공개했다면 금상첨화야.

2개정도 찾아보면 적당할 것 같네.

**Comment by qudgns5129** [comment]
그러면 연구자료 찾고 새로운 이슈로 찾아뵙겠습니다! ^^  
주말 잘 보내세요 교수님

**Comment by bytecell** [comment]
* 참고
  - https://www.egr.msu.edu/~mizhang/papers/2017_MobiSys_MobileDeepPill.pdf
  - https://www.computer.org/csdl/pds/api/csdl/proceedings/download-article/12OmNCfAPF1/pdf
  - https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8923984
