### ISSUE TITLE
관련 연구

### ISSUE THREAD

**Issue by qudgns5129** [qudgns5129/pill_classification#2]
전처리 관련 연구 링크 : https://github.com/emmaremy/pill-images
[모델 관련 연구 링크](http://www.dbpia.co.kr.eproxy.sch.ac.kr/journal/articleDetail?nodeId=NODE07995830,'relate_2')

**Comment by qudgns5129** [comment]
전처리 관련 연구는 NLMs Phil Image Acception Challenge라는 대회에서 진행한 내용 중, 모델 예측 하기 전에 중요한 전처리 단계를 작업하는 부분에 관한 논문입니다. 본문이 영어로 되어있기 때문에 오늘 중에 정리해서 링크 올리겠습니다.

**Comment by bytecell** [comment]
오키 나는 한글논문 한번 읽어보마.

**Comment by qudgns5129** [comment]
논문 정리 링크 : https://medium.com/byeonghuns-recording/personal-project-to-organize-related-research-1-c75aed6e5e68

**Comment by qudgns5129** [comment]
전처리 관련 논문을 읽으면서 느낀 것인데, 뭔가 참고할만한 사항이 없는거 같아서 다른 논문을 다시 서치해야할 거 같습니다.

**Comment by bytecell** [comment]
참고 URL:  https://github.com/adobe/antialiased-cnns

**Comment by qudgns5129** [comment]
<비교 논문>
- 알약 자동인식을 위한 딥러닝 모델 간 비교 및 검증 : http://www.dbpia.co.kr/journal/articleDetail?nodeId=NODE07995830
- 다양한 색상 및 형태를 갖는 알약의 자동 분류 시스템 : http://www.dbpia.co.kr/journal/articleDetail?nodeId=NODE07483903

**Comment by bytecell** [comment]
이 논문 괜찮아보여서 공유한다.

<h3>관련연구 리뷰: MobileDeepPill: A Small-Footprint Mobile Deep Learning System for Recognizing Unconstrained Pill Images (Xiao Zeng et al., 2017)</h3>

* URL: https://www.egr.msu.edu/~mizhang/papers/2017_MobiSys_MobileDeepPill.pdf

* 목적: 스마트폰 등을 사용하여 찍은 '알약' 사진을 사용하여, 기존 DB의 알약 사진과 매칭하여 어떤 알약인지 예측

* 방법
  - 모델
     - AlexNet 기반으로 3개의 CNN 모델을 independent 하게 학습
        - RGB 기반의 CNN
        - Gray-scale CNN
        - Gradient CNN
     - 모바일 기기에서 직접 동작하는 작은 규모의 모델을 만들기 위해 Knowledge distillation 기법 적용
  - Loss: 3개의 CNN 모델에 대하여 triplet loss function 적용
     - 스마트폰 등에서 찍은 consumer image 의 noise 에 대하여 robust 하도록 만들기 위해.
  - 데이터
     - data augmentation
        - 알약 DB에서 알약부분만 segmentation한 후, consumer image의 background와 synthetic image로 만듬
        - Gaussian filtering 기법을 통해 blurring
        - (0.8, 1.2) zooming
        - (-5, 5) translation (moving)
  - Feature: Sliding window & HOG 

* 실험
  - 성능측정
     - Mean average precision
     - Top-K accuracy
  - 2가지 recognition tasks
     - One-side pill recognition: 알약의 한쪽만 찍은 consumer image
     - Two-side pill recognition: 알약의 양쪽면을 모두 사용
  - 아`Student with KD`는 One-side task에 대하여 52.7% 정확도(top-1), 81.7% 정확도(top-5) 달성

* 감상평 & 의문점
  - 흥미로웠다. 실험부분은 훑어봤다.
  - 왜 old model인 AlexNet을 기반으로 설계했는지는 모르겠다.
  - Data augmentation 기법과 Triplet loss의 경우에는 타 연구에도 적용해볼만할 것 같다.

**Comment by qudgns5129** [comment]
감사합니다. 참고하겠습니다!

**Comment by qudgns5129** [comment]
정리 링크 : https://medium.com/byeonghuns-recording/personal-project-to-organize-related-research-2-3-223fe8edbebc

**Comment by qudgns5129** [comment]
다양한 색상 및 형태를 갖는 알약의 자동 분류 시스템  
--> 이 논문은 딥러닝 모델을 적용한 것이 아닌 기존 알약 분류 장치의 다른 방식 고안 방식이므로 제외하였습니다.

**Comment by qudgns5129** [comment]
깨진 알약을 분류하는 연구는 많으나, 깨진 알약을 어떤 약품인지 맞추는 연구는 계속 찾아봤지만 없는 거 같습니다. 그래서 그나마 유사한 연구인 깨진 알약을 분류하는 연구에 대한 자료입니다.  
깨진 아스피린 정제 감지를 위한 연구 : https://ieeexplore.ieee.org/abstract/document/5276427  
이중 IV2 비전 시스템을 이용하여 빠르게 이동하는 알약 탐지 및 분류하기 : https://www.researchgate.net/profile/Pham_Cat/publication/224354810_Detection_and_classification_of_pills_moving_at_a_very_high_speed_using_a_Bi-IV2_vision_system/links/09e4150a2a61ad84d6000000.pdf --> , Fig 8 밑에 부분에 깨진 알약의 누락된 부분 퍼센트를 계산하는 부분이 나오고, 결론 부분에 부서진 알약을 확인한다고 나옴(이게 확인만 하고 분류는 부서진 알약으로만 분류하는 거 같음 --> 제가 제대로 해석하였는지 확인 부탁드립니다ㅠㅠ)

**Comment by qudgns5129** [comment]
국내 학술지 논문 사이트 및 구글 학술 검색에서 검색하고 기본 구글에서 찾아보았습니다
