### ISSUE TITLE
문제 정의

### ISSUE THREAD

**Issue by qudgns5129** [qudgns5129/pill_classification#3]
문제 배경 : 대형 병원에서 환자의 호전 상태에 따라 처방이 바뀌거나 하는 일이 발생하면, 조제되었으나 투약되지 않은 약은 회수하게 된다. 약사는 이렇게 회수된 수백 종류의 알약을 재분류하는 작업을 하고 있다.
  
문제 정의 : 이미지의 색상 정보를 가지고 약품명 예측하기, 글자 인식 X -> 인간의 직관과 비슷한 모델을 만들기 위함(보다 직관적인)
  
< 모델 구조 >
detection + classification
전처리 단계 또는 모델 내 레이어 : 이미지에서 알약 detection 하기
INPUT : 이미지 RGB 3채널의 픽셀값
OUTPUT : 약품명
OUTPUT이 여러 개인 경우 고려 O -> multi-label classification
  
  
진행 순서 : ① 비교논문 서치 ② 전처리 방식 제고 ③ adobe 연구원의 antialiased-cnn 모델 적용하기
  
  
  
abode 모델 링크 : https://github.com/adobe/antialiased-cnns

**Comment by bytecell** [comment]
그래. 확인했다.

문제 정의한 것을 바탕으로,
데이터 상에서 input, output으로 무엇을 사용할지 명확히 결정하고,
output label 의 가짓수, 분포가 어떻게 되는지를 조사해보는 것으로 시작하자.

그런 후,
모델에 input을 넣고 학습시키는 코딩작업에 착수하면 될 것 같다.

**Comment by bytecell** [comment]
Detection 이니까 각 알약이 이미지의 어느 위치에 있는지도 '정답'이 필요할텐데, 데이터를 확인해봐야할 것 같다.

**Comment by qudgns5129** [comment]
네 알겠습니다!

**Comment by bytecell** [comment]
문제 정의에 기반해서,
데이터 준비가 끝나면 30% 이상은 이미 진전되었다고 봐도 된다.

데이터 준비가 끝나고 나면, rival method 를 사용하여 일단 실험을 돌려봐야 한다.
진행상황에 대해 조만간 만나서 얘기해보는게 좋겠다.
수요일이나 목요일 정도가 괜찮을 것 같다.

**Comment by qudgns5129** [comment]
내일 찾아 뵙도록 하겠습니다!

**Comment by qudgns5129** [comment]
rival method

1. AlexNet 기반의 CNN 모델 3개 o 
2. Yolov3
3. RetinaNet기반의 모델
4. Faster R-CNN 모델 o

method

1. abode antialiased-cnns


이것들 비교하면서 진행

우선 output label 의 가짓수, 분포가 어떻게 되는지를 조사해보는 것으로 시작
그 다음 비교 논문의 모델들에 대해 코드 짜보기

**Comment by qudgns5129** [comment]
최종 데이터 : https://nedrug.mfds.go.kr/pbp/CCBGA01/getItem?infoType=C&totalPages=4&limit=10&searchYn=true&page=1&&openDataInfoSeq=11  
데이터 이용관련 문의 : http://www.health.kr/notice/QnA_view.asp?show_idx=5673&search_value=&search_term=keyword&paging_value=1&setLine=100&setCategory=4  
  
약 2만 2천개의 이미지 데이터가 주소형태로 주어짐

**Comment by qudgns5129** [comment]
바뀐 데이터에 대해 약 품목명을 확인 한 결과 대부분의 품목명들이 unique한 값을 가지고 있는 것을 확인하였습니다. 이로 인해  출력값을 정하지 못하는 문제가 발생하였습니다. 
![image](https://user-images.githubusercontent.com/47845170/99268906-17265f80-2869-11eb-8b08-5589fb2f7063.png)
마지막 층을 unique 개수인 11936으로 설정하게 되면, train과 test를 나눈 데이터를 적용할 때, 
![image](https://user-images.githubusercontent.com/47845170/99269018-34f3c480-2869-11eb-84b1-34e5aa7d429e.png)
위와같은 출력값을 정하지 못하고 있습니다.

**Comment by bytecell** [comment]
정말로 약의 종류가 10000가지가 넘는 것인지 데이터를 확인해보면 좋겠다.

**Comment by bytecell** [comment]
맞추고자 하는 class label 이 '품목명' 인거야?
그렇다면 '분류번호'를 맞추도록 하는 건 어때?

**Comment by qudgns5129** [comment]
약의 종류가 10000가지가 넘는 걸로 확인되었습니다.(mg이 다른것도 다른 약으로 판단하게 될 시)  
분류번호(분류명)을 맞추는 것으로 넘어가야 할 거 같습니다

**Comment by qudgns5129** [comment]
분류번호를 맞추는 작업은 원형 데이터만 가지고 하면 데이터 불균형이 커서 train-test size를 6:4로 나누어야 하지만, 나중에 bbox부분을 develop시킨다면 train-test를 8:2정도로 나눠도 문제 없을 거 같습니다. 우선은 6:4로 나누어서 진행해보겠습니다.

**Comment by qudgns5129** [comment]
사용 모델
- AlexNet
- VGG16
- GoogLeNet
- ResNet50
  
평가 지표
- accuracy
- 생각해보기
