### ISSUE TITLE
Pill segmentation!! Help

### ISSUE THREAD

**Issue by qudgns5129** [qudgns5129/pill_classification#4]
알약부분만 segmentation한 후
![image](https://user-images.githubusercontent.com/47845170/97086978-a2914400-1661-11eb-9f77-ba147b0d9de0.png)  
위와 같은 이미지를 얻고 싶은데  
1. 이미지를 바이너리 이미지로 변환
2. sobel gradient 적용
3. 가장 바깥의 컨투어만 찾기(글자를 컨투어로 인식하여서 이를 없애기 위함)
이러한 방식으로 진행하게 되면
![image](https://user-images.githubusercontent.com/47845170/97087281-f8ff8200-1663-11eb-89de-bc2f3a17b314.png)
이런 이미지에 대해서는 잘 찾지만
![image](https://user-images.githubusercontent.com/47845170/97087291-0d437f00-1664-11eb-9a22-4638e325f4f1.png)
이렇게 알약이 작게 찍힌 이미지나, 줄자의 형태가 큰 데이터에 대해서는 이미지 분할을 못하게 됩니다...  
여러 필터를 입혀보았지만 sobel이 그나마 나은 필터였고, 교수님이 추천해주신 논문에서 Pill localization 하는 부분을 참고하여 방식을 구상하였지만, 저 논문에서는 아마 image가 좀 더 pure한 상태의 데이터에서 DB를 구축한 것으로 보여집니다... 어떻게 해야 segmentation을 더 잘할 수 있는지 자문을 구하고 싶습니다

**Comment by qudgns5129** [comment]
방식을 바꿔서 진행해보았습니다!
1. 이미지를 바이너리 스케일로 변환(이진 변환)
![image](https://user-images.githubusercontent.com/47845170/97089084-54d00800-1670-11eb-8844-f27eba593901.png)
![image](https://user-images.githubusercontent.com/47845170/97089081-4f72bd80-1670-11eb-9ba2-fadc24639fc0.png)
2. 모폴로지 침식 연산으로 원형 filtering
![image](https://user-images.githubusercontent.com/47845170/97089088-5bf71600-1670-11eb-86c8-6e19b1216816.png)
3. 나머지 일부 점들을 팽창 방법(opening)을 통해 제거(다시 팽창 연산을 해줘야지 변형이 안일어남)
![image](https://user-images.githubusercontent.com/47845170/97089174-1424be80-1671-11eb-9583-ab8229130514.png)
  
원본과 결과
원본 - ![image](https://user-images.githubusercontent.com/47845170/97089189-30c0f680-1671-11eb-9a39-e12d2552cf62.png)
결과 - ![image](https://user-images.githubusercontent.com/47845170/97089170-0d964700-1671-11eb-8b9a-419b84f9eec1.png)
-이런 데이터에 대해서는 좋은 방식인 것처럼 보여짐, 하지만 흰색 알약의 경우 이진변환을 할 때 제대로 인식하지 못하는 오류가 있음.
- 위에 올린 초록색 이미지 같은 곳에 적용 시
![image](https://user-images.githubusercontent.com/47845170/97090914-c9a44180-1672-11eb-8822-538e36355388.png)
![image](https://user-images.githubusercontent.com/47845170/97090919-d1fc7c80-1672-11eb-862a-d2233a72c82c.png)
여기서 부터 edge가 잘 인식이 안됨
![image](https://user-images.githubusercontent.com/47845170/97090921-d7f25d80-1672-11eb-9559-58dd19c98f0d.png)
![image](https://user-images.githubusercontent.com/47845170/97090926-e04a9880-1672-11eb-8e7b-b98eb3a182a1.png)
![image](https://user-images.githubusercontent.com/47845170/97090938-f48e9580-1672-11eb-8eb3-b47e435ec352.png)
결국 이렇게 컨투어를 엄청나게 많이 찾아버림. 이런 부분을 어떻게 개선할 지에 대해 의견좀 주실 수 있을까여?

**Comment by qudgns5129** [comment]
좀 더 general 한 segmentation model을 짜고 싶은데 생각보다 어려운 거 같습니다.  
이 문제만 해결된다면 resize 후 데이터를 저장하고, 그 후 일부분을 누락하여 일부러 데이터를 손실시키는 방법으로 전처리를 마칠 수 있을 거 같습니다.  
그 이후 모델 비교를 진행하면서 classification modeling을 진행하면 될 것으로 보입니다.

**Comment by bytecell** [comment]
결국 만들어내고자 하는 것은 '알약의 경계선'을 구하고자 하는 게 아니라 '알약을 포함하는 b-box'를 만들어내고자 하는 것이므로,
초록색 알약의 경우에는 찾아낸 '알약의 경계선'을 바탕으로 b-box를 자동으로 알아낼 수 있지 않을까 싶다.

예를 들어, 알약 경계선으로 찾아진 픽셀 중에서 '좌상단, 우상단, 좌하단, 우하단' 지점들을 찾아내서 이것들을 네모 모양으로 연결하면 b-box가 될 것 같다.

데이터 개수가 몇 개였지?
일단 자동적으로 위 방식으로 찾아내도록 한 다음, 눈으로 직접 한번씩 확인해봐야할 듯 싶다.
그런 다음, 이상하게 찾아진 녀석들만 직접 손으로 다시 데이터를 만들어주면 되지 않을까 싶다.

**Comment by qudgns5129** [comment]
데이터 레이블은 총 23223이며, 1개의 누락값빼고 23222개 입니다. 한번 b-box를 만들어보고 이상한 결과 확인해 보겠습니다.

**Comment by qudgns5129** [comment]
컨투어 - https://sosal.kr/1067

**Comment by qudgns5129** [comment]
예제 결과![image](https://user-images.githubusercontent.com/47845170/98415047-d89de180-20bf-11eb-9777-80c224b95459.png)

**Comment by qudgns5129** [comment]
컨투어 방식 예제 코드 링크 - https://sosal.kr/1067

예제 결과![image](https://user-images.githubusercontent.com/47845170/98415047-d89de180-20bf-11eb-9777-80c224b95459.png)

예제 결과 2
![image](https://user-images.githubusercontent.com/47845170/98415109-f66b4680-20bf-11eb-9426-5fd4f537a4dd.png)
예제 결과 3
![image](https://user-images.githubusercontent.com/47845170/98415140-097e1680-20c0-11eb-90f7-81f1d1797ce0.png)
  
  
- 이 코드는 밝은 알약의 윤곽선을 잘 찾지 못하는 경향이 있음
- 또한 width, height의 임계치를 직접 설정해야하기 때문에 모든 데이터에 대해 resize 후에 적용 시켜야 적합할 듯

**Comment by qudgns5129** [comment]
허프 변환 원 검출 방법
  
예제 결과 1
![image](https://user-images.githubusercontent.com/47845170/98415313-6d084400-20c0-11eb-887a-6000d161d1ce.png)
  
예제 결과 2
![image](https://user-images.githubusercontent.com/47845170/98415384-932de400-20c0-11eb-94f5-fcbb4d2feb16.png)
  
예제 결과 3
![image](https://user-images.githubusercontent.com/47845170/98415439-a8a30e00-20c0-11eb-87c6-871383e13cb1.png)

- 이 방식은 원형 검출에 뛰어난 성능을 보임, 색상도 고려할 필요 X
- 하지만 원형이 아닌 데이터는 아예 검출하지 못하는 한계 존재

**Comment by qudgns5129** [comment]
컨투어 방식 2 (모폴로지 연산)

예제 결과 1
![image](https://user-images.githubusercontent.com/47845170/98415983-a42b2500-20c1-11eb-9e75-2d2301e610f6.png)

예제 결과 2
![image](https://user-images.githubusercontent.com/47845170/98416012-af7e5080-20c1-11eb-95d6-60499849116c.png)

예제 결과 3
![image](https://user-images.githubusercontent.com/47845170/98416028-b5743180-20c1-11eb-81c8-f3d99f8d7400.png)

예제 결과 4
![image](https://user-images.githubusercontent.com/47845170/98416051-befd9980-20c1-11eb-8d65-f81aecdb2561.png)

예제 결과 5
![image](https://user-images.githubusercontent.com/47845170/98416149-e8b6c080-20c1-11eb-993c-98d9387c613d.png)

- 컨투어 방식의 전형적인 문제로 보여지는 흰색 검출의 어려움
- 알약 B-BOX 후에 쪼개진 알약 데이터 만들 때는 유용할 듯?

**Comment by qudgns5129** [comment]
- 컨투어 방식 2개와 허프변환 원검출 방법을 적용해보았습니다.
- 교수님은 어떻게 해야할 거 같다고 생각하시나요? 
  
- skimage를 사용하여 타원형 검출을 시도해 보았으나 오류로 잠시 멈춰있는 상태입니다.

**Comment by qudgns5129** [comment]
참고 : 위의 검출된 부분은 x,y,w,h 좌표 추출하여 바로 box이미지로 구축할 수 있습니다.

**Comment by bytecell** [comment]
결국 구하고자 하는 것은 bbox 좌표(예: 좌상단, 우하단 좌표)이므로, 
"흰색 타원형" 알약 빼고는 얼추 다 잡아냈다고 보여진다.

"흰색 타원형"만 제외하고 bbox 검출을 일단 진행해보고,
그 데이터만 가지고 일단 졸업논문을 진행해보는 게 어떨까?

그리고, "흰색 타원형" 데이터까지도 bbox 검출하는 방법에 대해서는,
졸업논문 이후에 "저널" 또는 "학술대회" 논문을 준비하면서 알아내면 괜찮지 않을까 싶다.

**Comment by qudgns5129** [comment]
네 감사합니다!

**Comment by qudgns5129** [comment]
b-box 결과
![image](https://user-images.githubusercontent.com/47845170/98461119-f7e65d00-21ec-11eb-9cb6-ea7ad793f59c.png)
결과가 나왔는데, 현재 방식(넓이가 80이상이고, 높이가 80 이상인 알약만 검출)으로 하게 되면 누락되는 알약들이 있습니다.(크기가 너무 작은 경우) 하지만 넓이와 높이를 낮추게 되면
![image](https://user-images.githubusercontent.com/47845170/98461149-35e38100-21ed-11eb-8cc4-d092d674f9e9.png)
위와 같이 작은 컨투어들도 인식하여 저장하게 되는 오류가 있습니다 ㅠ 좀 더 조정 해보거나 다른 방식 찾아보겠습니다.

**Comment by bytecell** [comment]
지금 일단 검출이 잘된 것들의 개수가 꽤 된다면, 그걸로 딥러닝 모델 학습을 일단 진행해보는게좋을것같다.

모델 학습이 잘되는것을 확인한후에 시간이 남으면,
검출이 잘안되는것들만 모아서 bbox 검출 시도를 계속해보는것도좋을듯하다.

**Comment by qudgns5129** [comment]
우선 검출이 잘 된 case만 가지고 모델학습을 진행해보고 결과에 대한 issue 올리겠습니다.

**Comment by bytecell** [comment]
그래. 알았다.
데이터 개수는 확인되는대로 이곳에 써줘.

**Comment by qudgns5129** [comment]
18564개입니다

**Comment by qudgns5129** [comment]
수정하겠습니다. 총 18170개이고, 결과는 밑의 사진과 같습니다
![image](https://user-images.githubusercontent.com/47845170/99232221-fcd28e80-2834-11eb-9504-7c297110ef8c.png)
