### ISSUE TITLE
논문 공공데이터 사용 가능 여부

### ISSUE THREAD

**Issue by qudgns5129** [qudgns5129/pill_classification#5]
의약품 안전나라 : https://nedrug.mfds.go.kr/cntnts/80  
위의 사이트에서 제공하는 공공데이터 개방 목록에 "의약품 낱알 식별" 라는 .csv 엑셀 데이터를 활용하였으며, 칼럼 중 '큰 제품 이미지' 칼럼에 첨부되어 있는 링크를 다 가져와서 이미지를 저장하였습니다.
  
개방 사이트에서는 데이터 사용 권한을 다음과 같이 명시하였습니다.
![image](https://user-images.githubusercontent.com/47845170/98417489-549a2880-20c4-11eb-8d7a-9cd486b0dd67.png)
  
이 데이터를 논문에서 사용할 수 있는건가요? 위의 내용 중  
"공공기관이 이용자에게 정보를 재활용할 수 있도록 제공하고, 제공받은 정보를 상업적, 비영리적으로 이용할 권한을 부여하는 것" 이라고 명시되어 있는데, 출처만 밝히면 되는 거 아닌가요?

**Comment by qudgns5129** [comment]
임의의 가공 금지 부분은 excel에만 해당하는 내용이고, 알약을 일부러 누락시키거나 변형시키는 것은 포함이 안되겠지요?

**Comment by bytecell** [comment]
우리는 직접 데이터를 공개할 것은 아니고,
해당 데이터에 대한 "bbox 좌표" 정보만 공개하는 것이기 때문에, 전혀 문제될 것이 없다고 생각한다.
